import { createDbConnection, getRawClient, type Transaction } from '@assertly/database';
import {
  DATABASE_CONNECTION,
  GLOBAL_RATE_LIMIT_TTL_MS,
  HealthModule,
  S3Module,
  ThrottlerBehindProxyGuard,
} from '@assertly/nestjs-common';
import { Module } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { APP_GUARD } from '@nestjs/core';
import { ThrottlerModule } from '@nestjs/throttler';
import { PostgreSqlDialect, PostgreSqlInboxDialect } from '@outboxy/dialect-postgres';
import { OutboxyModule } from '@outboxy/sdk-nestjs';

import { ConfigModule } from './modules/config/config.module';
import type { EnvConfig } from './modules/config/env.validation';
import { ResultProcessorModule } from './modules/result-processor/result-processor.module';
import { WebhookReceiverModule } from './modules/webhook-receiver/webhook-receiver.module';

const GLOBAL_RATE_LIMIT_MAX = 200;

@Module({
  imports: [
    ConfigModule,
    ThrottlerModule.forRoot([
      {
        ttl: GLOBAL_RATE_LIMIT_TTL_MS,
        limit: GLOBAL_RATE_LIMIT_MAX,
      },
    ]),
    HealthModule,
    OutboxyModule.forRootAsync({
      useFactory: () => ({
        dialect: new PostgreSqlDialect(),
        adapter: (tx: Transaction) => async (sql: string, params: unknown[]) => {
          const client = getRawClient(tx);
          // Safe: SQL is generated by @outboxy/dialect-postgres with parameterized queries, not user input
          return client.unsafe(sql, params as never[]);
        },
        inbox: {
          enabled: true,
          dialect: new PostgreSqlInboxDialect(),
        },
      }),
      isGlobal: true,
    }),
    S3Module.forRootAsync({
      inject: [ConfigService],
      useFactory: (...args: unknown[]) => {
        const config = args[0] as ConfigService<EnvConfig>;
        return {
          endpoint: config.getOrThrow<string>('MINIO_ENDPOINT'),
          region: 'us-east-1',
          accessKeyId: config.getOrThrow<string>('MINIO_APP_ACCESS_KEY'),
          secretAccessKey: config.getOrThrow<string>('MINIO_APP_SECRET_KEY'),
          useSSL: config.getOrThrow<string>('MINIO_USE_SSL') === 'true',
          bucket: config.getOrThrow<string>('MINIO_BUCKET'),
        };
      },
      isGlobal: true,
    }),
    WebhookReceiverModule,
    ResultProcessorModule,
  ],
  providers: [
    { provide: APP_GUARD, useClass: ThrottlerBehindProxyGuard },
    {
      provide: DATABASE_CONNECTION,
      inject: [ConfigService],
      useFactory: (config: ConfigService<EnvConfig>) => {
        const databaseUrl = config.getOrThrow<string>('DATABASE_URL');
        return createDbConnection(databaseUrl);
      },
    },
  ],
})
export class AppModule {}
