import type { Transaction } from '@spechive/database';
import { getRawClient } from '@spechive/database';

type QueryFn = (sql: string, params: unknown[]) => Promise<{ id: string }[]>;

export function createOutboxyAdapter(): (tx: Transaction) => QueryFn {
  return (tx: Transaction) => async (sql: string, params: unknown[]) => {
    const client = getRawClient(tx);
    // Safe: SQL is generated by @outboxy/dialect-postgres with parameterized queries, not user input
    return client.unsafe(sql, params as never[]);
  };
}
